### ISSUE TITLE
Enable Tokenizer Loading from downloaded Teacher Model

### ISSUE THREAD

**Issue by khaledsulayman** [instructlab/sdg#343]
Currently, the AutoTokenizer in the chunker tries to pull the tokenizer from the teacher model, but this hasn't been tested thoroughly outside of mixtral.

By default, `AutoTokenizer.from_pretrained()` will go to huggingface for the model, and in the case of mixtral, the repo is gated so you'd need to set `$HF_TOKEN`.

What should happen is we pull the tokenizer from the downloaded teacher model and raise an error if it cannot be found.

**Comment by bbrowning** [comment]
Something that came up is multiple downstream implementations will not have the teacher model on disk where the `ilab` CLI is run, and instead they run the teacher model in separate server processes that are not local to the container/machine running the CLI.

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Modify the chunking logic to use the local tokenizer from the downloaded teacher model instead of trying to fetch it from Hugging Face. This change ensures that the tokenizer is pulled from the local model and raises an error if it cannot be found.

I also created pull request: https://github.com/instructlab/sdg/pull/345


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by bbrowning** [comment]
@relyt0925 I'm tagging you into this for visibility - as part of the new chunking implementation in InstructLab, we'll attempt to use the actual tokenizer that the teacher model is using when chunking up documents. However, an implication of that is that we'll expect to be able to access that tokenizer from the `ilab` CLI process, which may not be available in your case as I believe you're running the teacher models separately and not on the same machine running the `ilab data generate` CLI.

This issue is to figure out how to handle loading this tokenizer model from the teacher, so if you have any input as a downstream user as to how we should handle falling back to something else if we can't find the teacher model's tokenizer, how users running teacher models outside of the CLI (via `--endpoint-url`) should get a tokenizer on-disk for the ilab CLI (or should they?), etc this is probably a good place to surface those concerns to the community.

**Comment by bbrowning** [comment]
Digging a bit into vllm, it has `/tokenize` and `/detokenize` endpoints added in https://github.com/vllm-project/vllm/pull/5054 . And, llama-cpp-python has `/extras/tokenize` added in https://github.com/abetlen/llama-cpp-python/pull/1136 . So, both of our default servers can give us a token count by calling an endpoint in the server as opposed to us needed to load and tokenize ourselves on the client-side. That seems cleaner to me, as we're guaranteed to already have the proper tokenizer loaded on the server and don't have to fuss with finding the tokenizer for the teacher model ourselves at all. The only reason this won't work is if we need to work with arbitrary servers that are not vllm or llama-cpp-python. Do we?

**Comment by khaledsulayman** [comment]
Something I just realized: we may want to decouple the tokenizer fetching from the actual model serving. 

Looking forward to a potential refactor, the doc ingestion stuff may have to happen before the teacher model gets served at all. Our code right now just happens to serve the model before reading the taxonomy preparing datasets, but it likely won’t stay that way.

**Comment by relyt0925** [comment]
@bbrowning sorry for missing this! We have a workaround for this now but I agree with everything you said.
